mobile:
    resource: "@MobileBundle/Controller/"
    type:     annotation
    prefix:   /

web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /

fantastic:
    resource: "@FantasticBundle/Controller/"
    type:     annotation
    prefix:   /

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /

util:
    resource: "@UtilBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
